spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourist_assistant?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: Touristassistantsystemno1!
  application:
    name: TouristAssistant
  web:
    resources:
      static-locations: file:/root/Touristassistantsystem/avatars/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    openai:
      #deepseek : sk-701fb2894a7c4f6fa36f776918af0c7b
      base-url: https://api.deepseek.com
      api-key: sk-701fb2894a7c4f6fa36f776918af0c7b
      chat:
        options:
          model: deepseek-reasoner
          temperature: 1.3
      embedding:
        api-key: sk-YqmJzeoBJhaNS9PI41165d59C62b41A7B8Cf07E41dCc01Cd
        base-url: https://api.xty.app
        options:
          model: text-embedding-ada-002
      audio:
        speech:
          base-url: https://api.xty.app
          api-key: sk-YqmJzeoBJhaNS9PI41165d59C62b41A7B8Cf07E41dCc01Cd


    vectorstore:
      redis:
        uri: redis://localhost:6379
        index: Travel
        prefix: "RAG"
        initialize-schema: true

wechat:
  appid: wx91e6a3712df5354b
  secret: 64e929552dfce9bb059c2cd93e45df46
  avatarPath: "/root/Touristassistantsystem/avatars/"

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.datateam.touristassistant.pojo

tencent:
  map:
    key: IEHBZ-XVLK4-3XTUF-FW2XR-3P7ES-SPBDO

#server:
#  port: 443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12



#      api-key: sk-Nmh1bJqY341KnM3akiAbha1Y9CNKsPu9lNS9C94L37nZSwpb
#      base-url: https://chatapi.littlewheat.com
