spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourist_assistant?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234

  application:
    name: TouristAssistant

  ai:
    openai:
      api-key: sk-8EvSZcQqQWRlb07l290b29A69a774e9e8aB38786E3E4D833
      base-url: https://api.xty.app


mybatis:
  configuration:
    map-underscore-to-camel-case: true