spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourist_assistant?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: TouristAssistant

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    openai:
      api-key: sk-Nmh1bJqY341KnM3akiAbha1Y9CNKsPu9lNS9C94L37nZSwpb
      base-url: https://chatapi.littlewheat.com
      chat:
        options:
          model: "gpt-3.5-turbo"
    vectorstore:
      redis:
        uri: redis://localhost:6379
        index: Travel
        prefix: "RAG"
        initialize-schema: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true