spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourist_assistant?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  application:
    name: TouristAssistant

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    openai:
#      api-key: sk-Nmh1bJqY341KnM3akiAbha1Y9CNKsPu9lNS9C94L37nZSwpb
      api-key: sk-dHDUtAqByl7UNfNjyuIB2FPV4taLHMN3jEKdd3LWlVQ0Khdi
      base-url: https://chatapi.littlewheat.com
#      base-url: https://api.xty.app
      chat:
        options:
          model: "gpt-4"
#              model: "gpt-3.5-turbo"
    vectorstore:
      redis:
        uri: redis://localhost:6379
        index: Travel
        prefix: "RAG"
        initialize-schema: true

wechat:
  appid: wx91e6a3712df5354b
  secret: 64e929552dfce9bb059c2cd93e45df46
  avatarPath: "C:/Users/28033/Desktop/TouristAssistant/uploads/avatars/"

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.datateam.touristassistant.pojo

tencent:
  map:
    key: IEHBZ-XVLK4-3XTUF-FW2XR-3P7ES-SPBDO


